services:
  build:
    build: .
    working_dir: /project
    volumes:
      - .:/project
    environment:
      - PICO_SDK_FETCH_FROM_GIT=1
    command: >
      bash -c "git config --global --add safe.directory /project && \
               git config --file .gitmodules --get-regexp path | awk '{print $$2}' | xargs -I{} git config --global --add safe.directory /project/{} && \
               git submodule update --init --recursive && \
               make build && \
               cp build/PicoSwitchWGA.uf2 ."
